"""initial migration

Revision ID: 4e7df46f1c4a
Revises: 
Create Date: 2025-11-05 17:47:20.699710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7df46f1c4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('MEMBER', 'HUB', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('WEEKLY_MEETING', 'NETWORKING', 'TRAINING', 'SPECIAL', name='eventtype'), nullable=False),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('business_category', sa.Enum('TECNOLOGIA', 'SAUDE', 'EDUCACAO', 'FINANCAS', 'MARKETING', 'CONSULTORIA', 'CONSTRUCAO', 'ALIMENTACAO', 'VAREJO', 'SERVICOS', 'INDUSTRIA', 'OUTROS', name='businesscategory'), nullable=False),
    sa.Column('company_description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('business_phone', sa.String(), nullable=True),
    sa.Column('business_email', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('LEAD', 'WATCHING_VIDEOS', 'QUESTIONNAIRE', 'PENDING_MEETING', 'APPROVED', 'REJECTED', 'ACTIVE', 'SUSPENDED', 'INACTIVE', name='memberstatus'), nullable=False),
    sa.Column('videos_watched', sa.Integer(), nullable=True),
    sa.Column('questionnaire_completed', sa.DateTime(), nullable=True),
    sa.Column('meeting_scheduled', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('total_referrals_given', sa.Integer(), nullable=True),
    sa.Column('total_referrals_received', sa.Integer(), nullable=True),
    sa.Column('total_deals_closed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('event_attendances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('member_id', sa.String(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('checked_in', sa.Boolean(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referrals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_member_id', sa.String(), nullable=False),
    sa.Column('to_member_id', sa.String(), nullable=False),
    sa.Column('client_name', sa.String(), nullable=False),
    sa.Column('client_company', sa.String(), nullable=True),
    sa.Column('client_phone', sa.String(), nullable=False),
    sa.Column('client_email', sa.String(), nullable=True),
    sa.Column('qualification', sa.Enum('HOT', 'WARM', 'COLD', name='qualification'), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('client_need', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONTACTED', 'NEGOTIATING', 'WON', 'LOST', 'CANCELLED', name='referralstatus'), nullable=False),
    sa.Column('contacted_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['to_member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('referral_id', sa.String(), nullable=False),
    sa.Column('given_by', sa.String(), nullable=False),
    sa.Column('was_well_served', sa.Boolean(), nullable=False),
    sa.Column('quality_rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('deal_closed', sa.Boolean(), nullable=True),
    sa.Column('deal_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['given_by'], ['members.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedbacks')
    op.drop_table('referrals')
    op.drop_table('event_attendances')
    op.drop_table('members')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
