"""add_visits_table

Revision ID: 8b923e9fa2d7
Revises: dc568069ef65
Create Date: 2025-11-07 02:53:44.078412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b923e9fa2d7'
down_revision: Union[str, None] = 'dc568069ef65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('visitor_id', sa.String(), nullable=False),
    sa.Column('visited_id', sa.String(), nullable=False),
    sa.Column('purpose', sa.Enum('CONHECER_SERVICOS', 'NETWORKING', 'PARCERIA', 'INDICACAO', 'FOLLOW_UP', 'OUTRO', name='visitpurpose'), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AGENDADA', 'REALIZADA', 'CANCELADA', 'NAO_REALIZADA', name='visitstatus'), nullable=False),
    sa.Column('visitor_notes', sa.Text(), nullable=True),
    sa.Column('visit_summary', sa.Text(), nullable=True),
    sa.Column('services_learned', sa.Text(), nullable=True),
    sa.Column('potential_referrals', sa.Text(), nullable=True),
    sa.Column('networking_quality', sa.Integer(), nullable=True),
    sa.Column('follow_up_needed', sa.String(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['visited_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visitor_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    # ### end Alembic commands ###
