"""add_profile_completion_fields

Revision ID: dc568069ef65
Revises: f8ae9763ac2e
Create Date: 2025-11-07 02:26:01.123068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc568069ef65'
down_revision: Union[str, None] = 'f8ae9763ac2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('facebook_url', sa.String(), nullable=True))
    op.add_column('members', sa.Column('twitter_url', sa.String(), nullable=True))
    op.add_column('members', sa.Column('interests', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('skills', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('profile_completed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'profile_completed')
    op.drop_column('members', 'skills')
    op.drop_column('members', 'interests')
    op.drop_column('members', 'twitter_url')
    op.drop_column('members', 'facebook_url')
    # ### end Alembic commands ###
